Repository OrdinaryRoad-Project/ordinaryroad-live-chat-client, pull requests merged in 2024-03, with the labels that each got.

#88 perf: 增加`IClientStatusChangeListener`接口，提供`void onStatusChange(Proper…
  README.md
  live-chat-client-commons/live-chat-client-commons-client/src/main/java/tech/ordinaryroad/live/chat/client/commons/client/BaseLiveChatClient.java
  live-chat-client-commons/live-chat-client-commons-client/src/main/java/tech/ordinaryroad/live/chat/client/commons/client/listener/IClientStatusChangeListener.java
  live-chat-clients/live-chat-client-bilibili/src/test/java/tech/ordinaryroad/live/chat/client/bilibili/client/BilibiliLiveChatClientTest.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/netty/handler/DouyinBinaryFrameHandler.java
  live-chat-clients/live-chat-client-douyin/src/test/java/tech/ordinaryroad/live/chat/client/douyin/client/DouyinLiveChatClientTest.java
  live-chat-clients/live-chat-client-douyu/src/main/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuLiveChatClient.java
  live-chat-clients/live-chat-client-douyu/src/test/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuLiveChatClientTest.java
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/ClientModeExample.java
  live-chat-clients/live-chat-client-kuaishou/src/test/java/tech/ordinaryroad/live/chat/client/kuaishou/client/KuaishouLiveChatClientTest.java
Labels: enhancement, chore

#89 perf: DouyinGiftCount
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/api/DouyinApis.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/msg/DouyinGiftMsg.java
  live-chat-clients/live-chat-client-douyin/src/test/java/tech/ordinaryroad/live/chat/client/douyin/client/DouyinLiveChatClientTest.java
Labels: enhancement

#91 feat msg forward
  live-chat-client-commons/live-chat-client-commons-base/pom.xml
  live-chat-client-commons/live-chat-client-commons-client/pom.xml
  live-chat-client-commons/live-chat-client-commons-client/src/main/java/tech/ordinaryroad/live/chat/client/commons/client/config/BaseLiveChatClientConfig.java
  live-chat-client-commons/live-chat-client-commons-util/pom.xml
  live-chat-client-commons/pom.xml
  live-chat-client-examples/client-example/pom.xml
  live-chat-client-examples/handler-example/pom.xml
  live-chat-client-examples/pom.xml
  live-chat-client-servers/live-chat-client-servers-netty-client/pom.xml
  live-chat-client-servers/live-chat-client-servers-netty-client/src/main/java/tech/ordinaryroad/live/chat/client/servers/netty/client/base/BaseNettyClient.java
  live-chat-client-servers/live-chat-client-servers-netty/pom.xml
  live-chat-client-servers/pom.xml
  live-chat-clients/live-chat-client-bilibili/pom.xml
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/client/BilibiliLiveChatClient.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/listener/impl/BilibiliForwardMsgListener.java
  live-chat-clients/live-chat-client-douyin/pom.xml
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/client/DouyinLiveChatClient.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/listener/impl/DouyinForwardMsgListener.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/msg/DouyinDanmuMsg.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/msg/DouyinEnterRoomMsg.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/msg/DouyinGiftMsg.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/msg/DouyinLikeMsg.java
  live-chat-clients/live-chat-client-douyu/pom.xml
  live-chat-clients/live-chat-client-douyu/src/main/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuLiveChatClient.java
  live-chat-clients/live-chat-client-douyu/src/main/java/tech/ordinaryroad/live/chat/client/douyu/listener/impl/DouyuForwardMsgListener.java
  live-chat-clients/live-chat-client-huya/pom.xml
  live-chat-clients/live-chat-client-huya/src/main/java/tech/ordinaryroad/live/chat/client/huya/client/HuyaLiveChatClient.java
  live-chat-clients/live-chat-client-huya/src/main/java/tech/ordinaryroad/live/chat/client/huya/listener/impl/HuyaForwardMsgListener.java
  live-chat-clients/live-chat-client-kuaishou/pom.xml
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/client/KuaishouLiveChatClient.java
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/listener/impl/KuaishouForwardMsgListener.java
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/msg/KuaishouDanmuMsg.java
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/msg/KuaishouGiftMsg.java
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/msg/KuaishouLikeMsg.java
  live-chat-clients/live-chat-client-websocket/pom.xml
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/client/WebSocketLiveChatClient.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/config/WebSocketLiveChatClientConfig.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/constant/WebSocketCmdEnum.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/listener/IWebSocketConnectionListener.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/listener/IWebSocketMsgListener.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/msg/WebSocketMsg.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/msg/base/IWebSocketMsg.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/netty/handler/WebSocketBinaryFrameHandler.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/netty/handler/WebSocketConnectionHandler.java
  live-chat-clients/live-chat-client-websocket/src/test/java/tech/ordinaryroad/live/chat/client/websocket/client/WebSocketLiveChatClientTest.java
  live-chat-clients/pom.xml
  pom.xml
Labels: enhancement

#95 fix: 修复B站无法使用问题，优化B站流程
  live-chat-client-commons/live-chat-client-commons-util/src/main/java/tech/ordinaryroad/live/chat/client/commons/util/OrLiveChatCookieUtil.java
  live-chat-client-commons/live-chat-client-commons-util/src/main/java/tech/ordinaryroad/live/chat/client/commons/util/OrLiveChatHttpUtil.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/api/BilibiliApis.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/client/BilibiliLiveChatClient.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/config/BilibiliLiveChatClientConfig.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/netty/frame/AuthWebSocketFrame.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/netty/frame/HeartbeatWebSocketFrame.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/netty/frame/factory/BilibiliWebSocketFrameFactory.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/netty/handler/BilibiliConnectionHandler.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/util/BilibiliCodecUtil.java
  live-chat-clients/live-chat-client-bilibili/src/test/java/tech/ordinaryroad/live/chat/client/bilibili/api/BilibiliApisTest.java
  live-chat-clients/live-chat-client-bilibili/src/test/java/tech/ordinaryroad/live/chat/client/bilibili/client/BilibiliLiveChatClientTest.java
Labels: bug

#99 Fix 98 handshake timeout
  live-chat-client-commons/live-chat-client-commons-client/src/main/java/tech/ordinaryroad/live/chat/client/commons/client/config/BaseLiveChatClientConfig.java
  live-chat-client-servers/live-chat-client-servers-netty-client/src/main/java/tech/ordinaryroad/live/chat/client/servers/netty/client/base/BaseNettyClient.java
  live-chat-clients/live-chat-client-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/bilibili/client/BilibiliLiveChatClient.java
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/client/DouyinLiveChatClient.java
  live-chat-clients/live-chat-client-douyu/src/main/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuDanmuLiveChatClient.java
  live-chat-clients/live-chat-client-douyu/src/main/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuWsLiveChatClient.java
  live-chat-clients/live-chat-client-huya/src/main/java/tech/ordinaryroad/live/chat/client/huya/client/HuyaLiveChatClient.java
  live-chat-clients/live-chat-client-kuaishou/src/main/java/tech/ordinaryroad/live/chat/client/kuaishou/client/KuaishouLiveChatClient.java
  live-chat-clients/live-chat-client-websocket/src/main/java/tech/ordinaryroad/live/chat/client/websocket/client/WebSocketLiveChatClient.java
Labels: bug

#101 Feat 100 dynamic websocketuri
  live-chat-client-commons/live-chat-client-commons-util/src/main/java/tech/ordinaryroad/live/chat/client/commons/util/OrLiveChatUrlUtil.java
  live-chat-client-servers/live-chat-client-servers-netty-client/src/main/java/tech/ordinaryroad/live/chat/client/servers/netty/client/base/BaseNettyClient.java
  live-chat-clients/live-chat-client-douyu/src/main/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuLiveChatClient.java
  live-chat-clients/live-chat-client-douyu/src/test/java/tech/ordinaryroad/live/chat/client/douyu/client/DouyuLiveChatClientTest.java
Labels: enhancement

#107 优化抖音的礼物数量判断
  live-chat-clients/live-chat-client-douyin/src/main/java/tech/ordinaryroad/live/chat/client/douyin/api/DouyinApis.java
Labels: enhancement
